"""inicializando o banco

Revision ID: 0bbbeefac050
Revises: 
Create Date: 2025-10-27 23:50:11.665038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbbeefac050'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bibliotecas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isbn', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('sinopse', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('autor', sa.String(), nullable=True),
    sa.Column('data_lancamento', sa.String(), nullable=True),
    sa.Column('imagem_capa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biblioteca_livros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_livro', sa.Integer(), nullable=False),
    sa.Column('fk_biblioteca', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fk_biblioteca'], ['bibliotecas.id'], ),
    sa.ForeignKeyConstraint(['fk_livro'], ['livros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('biblioteca_mae', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['biblioteca_mae'], ['bibliotecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_livros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_biblioteca_livro', sa.Integer(), nullable=False),
    sa.Column('data_solicitacao', sa.String(), nullable=False),
    sa.Column('data_retirada', sa.String(), nullable=False),
    sa.Column('data_devolucao', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_biblioteca_livro'], ['biblioteca_livros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_livros')
    op.drop_table('usuarios')
    op.drop_table('biblioteca_livros')
    op.drop_table('livros')
    op.drop_table('bibliotecas')
    # ### end Alembic commands ###
