"""criando a coluna senha na tabela de bibliotecas

Revision ID: 0c43039d7988
Revises: 0bbbeefac050
Create Date: 2025-10-28 11:32:14.258420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c43039d7988'
down_revision: Union[str, Sequence[str], None] = '0bbbeefac050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bibliotecas', sa.Column('senha', sa.String(), nullable=False))
    op.add_column('bibliotecas', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bibliotecas', 'email')
    op.drop_column('bibliotecas', 'senha')
    # ### end Alembic commands ###
